### ISSUE TITLE
Prompt / commandline broken after quitting 8play

### ISSUE THREAD

**Issue by qwerty007** [jgmp/8play#1]
When I quit 8play, the prompt needs a 'reset' to get back into a working condition.
When pressing 'enter' I get a new prompt, but on the same line. I can type, but the characters aren't displayed. Another ^C doesn't help. A workaround is to use a function that adds 'reset' e.g. '8play <url> ; reset'. I don't know C, but maybe the part that displays the track time needs to be fixed.

Happens in tmux, in st and in the tty too.

**Comment by jgmp** [comment]
Thanks for the feedback.  Somehow my shell (mksh) prevented me from noticing this. I fixed the reset function.  A typo in a check prevented it from running...

Could you let me know if this fixes the problem for you?

**Comment by qwerty007** [comment]
Fixed, thanks.
