### ISSUE TITLE
Add support for other players / enable scrobbling support

### ISSUE THREAD

**Issue by shatteringlass** [jgmp/8play#2]
I usually scrobble my mpv plays, but this wonderful command line app of yours plays via its own media player and I can't figure a way to add scrobbling support (for last.fm scrobble feature). Are you interested in providing support? Thanks

**Comment by jgmp** [comment]
Thank you for your interest and this suggestion.  I will add scrobbling support shortly.

**Comment by jgmp** [comment]
last.fm is currently not giving out new API keys.  Scrobbling support has to be put on hold until new API keys are available.

**Comment by shatteringlass** [comment]
Understood. But a temporary workaround would be to use one's old API keys
to scrobble listens. Would you be interested? Thanks btw

2015-10-27 13:42 GMT+01:00 Johannes Postma <notifications@github.com>:

**Comment by jgmp** [comment]
I should have read last.fm terms and conditions before stating that I would add support.  I am sorry for that. Their deprecated API for scrobbling is good, but they are not issuing any new clientids and I cannot accept the terms and conditions that come with the new API.  It includes way more than just the scrobbling part. And I don't like the idea of everyone supplying their own API key and secret.

I am sorry about the confusion but I wont add support for scrobbling.

Adding support for other players wont help in this case.  The media stream itself does not contain the track and artist name, they are supplied separately by 8tracks.com. In other words, the players will just see a file without knowing the artist or track name and has nothing to scrobble about.

**Comment by shatteringlass** [comment]
Ok, I respect your decision.
